Homework 12. Cypress locators
Sviatilishe/ngx-cypress-test pull request #2
Opened 2023-10-13 20:59 UTC by Sviatilishe

2023-10-13 23:00 UTC, sttaran requested changes

2023-10-13 23:00 UTC, sttaran commented on cypress/e2e/test-app/test2.cy.js
> +    cy.get("ngx-dialog-name-prompt nb-card-body input").should("exist");
Use should "be visible ". Elements can exist but be hidden

2023-10-14 07:19 UTC, Sviatilishe commented on cypress/e2e/test-app/test2.cy.js
> +    cy.get("ngx-dialog-name-prompt nb-card-body input").should("exist");
thanks, pushed changes

2023-10-14 12:12 UTC, sttaran requested changes

2023-10-14 12:12 UTC, sttaran commented on cypress.config.ts
> +    screenshotsFolder: 'C:/Autotests/cypress-screens',
Remove this line

2023-10-17 11:52 UTC, merged